name: login
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter


  # -- icon packages
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  line_awesome_flutter: ^3.0.1

  curved_navigation_bar: ^1.0.6 
  flutter_native_splash: ^2.4.3
  get: ^4.6.6
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.2.0+3
  flutter_otp_text_field: ^1.2.0

  # -- firebase packages
  firebase_core : ^3.8.0
  firebase_auth: ^5.3.3


 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_native_splash:
  android: true
  ios: true
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/images/splash_screen_image.png
  image_dark: assets/images/splash_screen_image.png

  # andriod_12:
  #   image: assets/images/car1.png
  #   icon_background_color: "#f7f6f1"
  #   image_dark: assets/images/car1.png
  #   icon_background_color_dark: "#272727"

flutter:
  uses-material-design: true

  assets:
    # - assets/images/splash/splash_screen_image.png
    # - assets/images/splash/splash_screen_text.png
    # - assets/images/car.png
    - assets/images/
    - assets/images/splash/
    - assets/images/bording/
    - assets/images/welcome_images/
    - assets/logo/
    - assets/images/loginsignup/
    - assets/images/forget_password/
    - assets/images/dash/
    - assets/images/profile/


    









  #   - images/a_dot_ham.jpeg



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700